CC=gcc
CFLAGS=-I.

all : eeprom_2464 mac_24AA02E48T

eeprom_2464: eeprom_2464.c
	$(CC) eeprom_2464.c -o eeprom_2464 -I.

mac_24AA02E48T: mac_24AA02E48T.c
	$(CC) mac_24AA02E48T.c -o mac_24AA02E48T -I.
